#!/usr/bin/env python3
"""Computation core for review-ablation.sh — arm building and the joint statistic.

review-ablation.sh owns the CLI, the receipt/manifest guards, and the jq work.
This file owns the two parts that need real computation:

  arm    resolve the enumerated span table against a baseline tree, apply an
         ablation, and prove it took effect by VERBATIM SPAN MATCH against the
         enumerated spec.
  stats  the pre-registered decision rule: single-step Westfall-Young max-T over
         the full C(2N,N)^M label-assignment space.

Stdlib only. Python 3.8+ and jq are already kc-pr-flow runtime dependencies
(review-runtime-safe-io.py), so this adds none.

WHY THE POST-CONDITION CHECKS THE SPEC, NOT THE PATCH
-----------------------------------------------------
The span set checked after an ablation is the ENUMERATED SPEC — every CUT span
the table names — never the set of spans the builder happened to apply. Checking
only what was applied asks the builder to grade its own homework: it agrees with
itself by construction and cannot fail. That is the same defect shape as proving
absence with the keywords you chose to grep for, and it is why the keyword grep
below is a canary rather than the proof: of the 11 CUT spans, four (S2, S3, S4,
S10) contain none of the four keyword patterns, so an arm that removed only the
keyword-bearing spans would leave the gate's failure-class table, its demotion
rule, its framework-meta sub-rule and the entire per-agent instruction blockquote
on disk while the keyword post-condition reported it clean.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import pathlib
import re
import shutil
import statistics
import sys

# ------------------------------------------------------------------ span table

SKILL = "skills/kc-pr-review/SKILL.md"
TRIAGE = "reference/review-triage.md"
LEARNED = "reference/learned-patterns.md"

# The substring S6 removes, and the rule that must survive that removal.
S6_REMOVE = " after the verification gate"
S6_KEEP = "**Apply confidence gates**"

# The keyword sweep, retained as a CANARY only: a residual hit outside the
# whitelist means the enumeration table missed a site. A clean canary proves
# nothing on its own.
KEYWORD_PATTERNS = (r"pre-emit", r"quote-the-line", r"§6a quote", r"verification gate")
STEP25_WHITELIST = "Step 2.5 builds a verification gate from explicit concerns"

DIMENSIONS = ("anchor_set", "severity_mix", "tokens")
SEVERITIES = ("CRITICAL", "HIGH", "MEDIUM", "LOW", "NIT")

CERTIFIES = {
    "null_result": (
        "material:false certifies no detected difference on the measured dimensions "
        "(anchor set, severity mix, tokens) at alpha=0.05 for the corpus, sizing, and "
        "model recorded in this verdict. It is never a certificate of 'no behavioral "
        "change': a cut that rewords a finding while its anchor and claim_key hold is "
        "outside the instrument's range by construction, as is any effect below the "
        "power floor."
    ),
    "detection_scope": (
        "A material:true verdict on a multi-file, multi-span removal certifies detection "
        "of a LARGE removal only. It does not establish sensitivity to a small or "
        "wording-only cut: at N=3/M=3 the measured detection knee is between +1 and +2 "
        "findings per run, so an effect worth one extra finding per run is missed about "
        "two times in three. A downstream cut may not cite this verdict as evidence its "
        "own smaller cut would have been detected."
    ),
}


def die(msg):
    sys.stderr.write("review-ablation: %s\n" % msg)
    raise SystemExit(1)


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def load_table(path):
    """Read the enumerated span table + pins sidecar.

    Columns: id, relpath, start, end, kind, sha256. The sha column is the pin;
    it is generated by --write-pins from a tree, never hand-typed, because a
    hand-typed hash is a number written before it was computed.
    """
    rows = []
    for raw in pathlib.Path(path).read_text(encoding="utf-8").split("\n"):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 6:
            die("span table row is malformed (want 6 tab-separated columns): %r" % raw)
        sid, relpath, start, end, kind, pin = parts
        if kind not in ("cut", "cut_sub", "keep"):
            die("span table row %s has unknown kind %r" % (sid, kind))
        rows.append(
            {"id": sid, "path": relpath, "start": int(start), "end": int(end),
             "kind": kind, "pin": pin}
        )
    if not rows:
        die("span table is empty — there is nothing to prove was removed")
    return rows


def extract(tree, relpath, start, end):
    body = (tree / relpath).read_text(encoding="utf-8").split("\n")
    return "\n".join(body[start - 1:end])


def resolve(tree, rows, check_pins=True):
    """Resolve every enumerated span against the tree and verify its pin.

    The pins are the authority. A span whose text no longer hashes to its pin
    means the tree moved under the table — that is a signal to re-derive the
    enumeration, never to hand-adjust the line numbers so the pins pass.
    """
    resolved = {}
    drift = []
    for row in rows:
        target = tree / row["path"]
        if not target.is_file():
            die("enumerated file is missing from the tree: %s" % row["path"])
        text = extract(tree, row["path"], row["start"], row["end"])
        if not text.strip():
            die("%s resolved to empty text — the tree moved under the table" % row["id"])
        got = sha(text)
        if check_pins and got != row["pin"]:
            drift.append(
                "%s (%s:%d-%d) does not match its pin (want %s, got %s)"
                % (row["id"], row["path"], row["start"], row["end"], row["pin"][:12], got[:12])
            )
        entry = dict(row)
        entry["text"] = text
        entry["sha256"] = got
        resolved[row["id"]] = entry
    if drift:
        die(
            "span pins do not match the tree:\n  "
            + "\n  ".join(drift)
            + "\n  the pins are the authority; re-derive the enumeration rather than "
              "editing line numbers until they pass"
        )
    return resolved


def keyword_visible(text):
    return any(re.search(p, text, re.IGNORECASE) for p in KEYWORD_PATTERNS)


# ----------------------------------------------------------------- arm building


def remove_span(tree, relpath, text, sid):
    path = tree / relpath
    body = path.read_text(encoding="utf-8")
    n = body.count(text)
    if n != 1:
        die(
            "%s occurs %d times in %s, expected exactly 1 — a patch that matches "
            "more than one place removes the wrong one and still reports success"
            % (sid, n, relpath)
        )
    path.write_text(body.replace(text + "\n", "", 1), encoding="utf-8")


def remove_substring(tree, relpath, sub, sid):
    path = tree / relpath
    body = path.read_text(encoding="utf-8")
    n = body.count(sub)
    if n != 1:
        die("%s substring occurs %d times in %s, expected exactly 1" % (sid, n, relpath))
    path.write_text(body.replace(sub, "", 1), encoding="utf-8")


def span_postcondition(tree, resolved, ablated):
    """Verbatim span match against the ENUMERATED SPEC.

    ablated=True  every CUT span must be absent; every KEEP span present and
                  byte-identical; S6's surviving half still there.
    ablated=False (arm A / A_prime) every enumerated span must be present and
                  byte-identical — an unablated arm that lost text is not a
                  baseline.
    """
    violations = []
    for entry in resolved.values():
        body = (tree / entry["path"]).read_text(encoding="utf-8")
        probe = S6_REMOVE if entry["kind"] == "cut_sub" else entry["text"]
        if entry["kind"] == "keep":
            if entry["text"] not in body:
                violations.append(
                    "%s (%s): KEEP span missing or modified — cutting it would ablate a "
                    "second, independent mechanism and confound the comparison"
                    % (entry["id"], entry["path"])
                )
        elif ablated:
            if probe in body:
                violations.append(
                    "%s (%s:%d-%d): CUT span still present in the ablated arm"
                    % (entry["id"], entry["path"], entry["start"], entry["end"])
                )
        else:
            if entry["text"] not in body:
                violations.append(
                    "%s (%s): span missing from an UNABLATED arm" % (entry["id"], entry["path"])
                )
    if ablated and S6_KEEP not in (tree / SKILL).read_text(encoding="utf-8"):
        violations.append(
            "S6 (%s): the surviving '%s' rule was lost — S6 is an edit, not a cut"
            % (SKILL, S6_KEEP)
        )
    return violations


def keyword_canary(tree, resolved):
    """Residual keyword hits outside the whitelist. A CANARY, never the proof.

    A hit means the enumeration table missed a site. Absence of hits means
    nothing on its own, which is the whole reason span match exists.
    """
    residual = []
    for relpath in sorted({e["path"] for e in resolved.values()}):
        path = tree / relpath
        if not path.is_file():
            continue
        for i, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
            if STEP25_WHITELIST in line:
                continue
            if keyword_visible(line):
                residual.append("%s:%d" % (relpath, i))
    return residual


def cmd_arm(args):
    baseline = pathlib.Path(args.tree).resolve()
    dest = pathlib.Path(args.dest).resolve()
    rows = load_table(args.table)

    if not (baseline / SKILL).is_file():
        die("no %s under %s — that is not a kc-pr-flow tree" % (SKILL, baseline))
    if dest.exists():
        die("destination already exists: %s" % dest)

    resolved = resolve(baseline, rows)
    ablated = args.arm not in ("A", "A_prime")

    spec_cuts = [e["id"] for e in resolved.values() if e["kind"] != "keep"]
    if args.spans is None:
        applied = spec_cuts if ablated else []
    else:
        applied = [s for s in args.spans.split(",") if s]
        unknown = [s for s in applied if s not in resolved]
        if unknown:
            die("unknown span ids: %s" % ", ".join(unknown))
    if ablated and not applied:
        die("the selected span set is empty — an ablated arm that removes nothing "
            "is not an arm, and an empty baseline hit set proves nothing")

    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(baseline, dest)

    # Apply in reverse spec order so earlier removals cannot disturb later
    # verbatim lookups within the same file.
    for sid in sorted(applied, key=lambda s: (resolved[s]["path"], -resolved[s]["start"])):
        entry = resolved[sid]
        if entry["kind"] == "cut_sub":
            remove_substring(dest, entry["path"], S6_REMOVE, sid)
        else:
            remove_span(dest, entry["path"], entry["text"], sid)

    violations = span_postcondition(dest, resolved, ablated)
    residual = keyword_canary(dest, resolved) if ablated else []

    if violations:
        die(
            "arm %s failed the span-match post-condition:\n  " % args.arm
            + "\n  ".join(violations)
        )
    if residual:
        die(
            "arm %s failed the keyword canary at %s — a residual hit means the "
            "enumeration table missed a site" % (args.arm, ", ".join(residual))
        )

    manifest = {
        "schema": "kc-pr-flow.ablation-arm-manifest/v1",
        "arm": args.arm,
        "baseline_tree_skill_sha256": sha((baseline / SKILL).read_text(encoding="utf-8")),
        "skill_sha256": sha((dest / SKILL).read_text(encoding="utf-8")),
        "spans": [
            {"id": e["id"], "path": e["path"], "start": e["start"], "end": e["end"],
             "kind": e["kind"], "sha256": e["sha256"],
             "keyword_visible": keyword_visible(e["text"]),
             "applied": e["id"] in applied}
            for e in resolved.values()
        ],
        "applied_spans": sorted(applied),
        "spec_cut_spans": sorted(spec_cuts),
        "post_condition": {
            "span_match": "pass",
            "span_match_authority": "the enumerated span table, not the applied patch set",
            "keyword_grep": "clean",
            "keyword_grep_role": "canary",
        },
    }
    manifest["arm_manifest_sha256"] = sha(
        json.dumps(manifest, sort_keys=True, separators=(",", ":"))
    )
    (dest / "arm-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(manifest["arm_manifest_sha256"])
    return 0


def cmd_write_pins(args):
    """Regenerate the pins sidecar from a tree. Never hand-type a pin."""
    baseline = pathlib.Path(args.tree).resolve()
    rows = load_table(args.table)
    resolved = resolve(baseline, rows, check_pins=False)
    out = []
    for row in rows:
        e = resolved[row["id"]]
        out.append("\t".join([e["id"], e["path"], str(e["start"]), str(e["end"]),
                              e["kind"], e["sha256"]]))
    sys.stdout.write("\n".join(out) + "\n")
    return 0


# ------------------------------------------------------ the decision rule


def jaccard(a, b):
    if not a and not b:
        return 1.0
    return len(a & b) / len(a | b)


def hist_similarity(h1, h2):
    return 1.0 - 0.5 * sum(abs(x - y) for x, y in zip(h1, h2))


def histogram(severities):
    """Six categories: the five severities plus a dedicated EMPTY.

    Without EMPTY the normalization divides by zero on a legitimate
    zero-finding receipt. With it, an empty run and a non-empty run sit at
    total-variation distance 1 and two empty runs at distance 0.
    """
    counts = [0] * len(SEVERITIES)
    for s in severities:
        if s not in SEVERITIES:
            die("unknown severity %r — the skill's vocabulary is %s"
                % (s, "/".join(SEVERITIES)))
        counts[SEVERITIES.index(s)] += 1
    total = sum(counts)
    if total == 0:
        return [0.0] * len(SEVERITIES) + [1.0]
    return [c / total for c in counts] + [0.0]


def splits(two_n, n):
    out = []
    for a in itertools.combinations(range(two_n), n):
        out.append((a, tuple(i for i in range(two_n) if i not in a)))
    return out


def pairwise(items, simfn):
    k = len(items)
    m = [[0.0] * k for _ in range(k)]
    for i in range(k):
        for j in range(i + 1, k):
            m[i][j] = m[j][i] = simfn(items[i], items[j])
    return m


def agreement_D(sim, a_idx, b_idx):
    within_a = statistics.fmean([sim[i][j] for i, j in itertools.combinations(a_idx, 2)])
    within_b = statistics.fmean([sim[i][j] for i, j in itertools.combinations(b_idx, 2)])
    between = statistics.fmean([sim[i][j] for i in a_idx for j in b_idx])
    return (within_a + within_b) / 2.0 - between


def scalar_D(values, a_idx, b_idx):
    return statistics.fmean([values[i] for i in a_idx]) - statistics.fmean(
        [values[i] for i in b_idx]
    )


def per_pr_D_table(runs, split_list):
    anchors = pairwise([set(r["fingerprints"]) for r in runs], jaccard)
    sevs = pairwise([histogram(r["severities"]) for r in runs], hist_similarity)
    toks = [float(r["tokens"]) for r in runs]
    return [
        (agreement_D(anchors, a, b), agreement_D(sevs, a, b), scalar_D(toks, a, b))
        for a, b in split_list
    ]


def joint_test(d_tables, alpha):
    """Single-step Westfall-Young max-T over the full assignment space.

    Assignment 0 — split 0 in every PR — is the observed labelling, which is why
    the caller must order each PR's runs as [arm X runs..., arm Y runs...].
    """
    m = len(d_tables)
    n_dims = len(DIMENSIONS)

    totals = [[0.0] * n_dims]
    for pr_rows in d_tables:
        abs_rows = [tuple(abs(v) for v in row) for row in pr_rows]
        totals = [
            [acc[d] + row[d] for d in range(n_dims)] for acc in totals for row in abs_rows
        ]
    ts = [[acc[d] / m for d in range(n_dims)] for acc in totals]
    observed = ts[0]

    means = [statistics.fmean([t[d] for t in ts]) for d in range(n_dims)]
    sds = [statistics.pstdev([t[d] for t in ts]) for d in range(n_dims)]

    def z(t, d):
        # A dimension that does not vary over the assignment space carries no
        # signal; standardizing it would divide by zero.
        return 0.0 if sds[d] == 0.0 else (t[d] - means[d]) / sds[d]

    maxz = [max(z(t, d) for d in range(n_dims)) for t in ts]
    obs_z = [z(observed, d) for d in range(n_dims)]
    total = len(ts)

    p_joint = sum(1 for v in maxz if v >= max(obs_z) - 1e-12) / total
    p_dim = {
        DIMENSIONS[d]: sum(1 for v in maxz if v >= obs_z[d] - 1e-12) / total
        for d in range(n_dims)
    }
    return p_joint, p_dim, observed, total


def cmd_stats(args):
    payload = json.load(sys.stdin)
    arm_x, arm_y = args.arms.split(",", 1)
    records = payload["runs"]

    prs = sorted({r["pr"] for r in records})
    if not prs:
        die("no runs to compare")

    d_tables = []
    per_pr = []
    n = None
    runs_compared = 0
    for pr in prs:
        xs = sorted([r for r in records if r["pr"] == pr and r["arm"] == arm_x],
                    key=lambda r: r["run_index"])
        ys = sorted([r for r in records if r["pr"] == pr and r["arm"] == arm_y],
                    key=lambda r: r["run_index"])
        if len(xs) != len(ys):
            die("PR %s has %d runs on arm %s but %d on arm %s — the permutation test "
                "requires balanced arms" % (pr, len(xs), arm_x, len(ys), arm_y))
        if len(xs) < 2:
            die("PR %s has %d runs per arm; N must be at least 2 for a within-arm "
                "agreement to exist" % (pr, len(xs)))
        if n is None:
            n = len(xs)
        elif n != len(xs):
            die("unbalanced sizing: PR %s has N=%d, earlier PRs had N=%d" % (pr, len(xs), n))
        runs_compared += len(xs) + len(ys)
        rows = per_pr_D_table(xs + ys, splits(2 * n, n))
        d_tables.append(rows)
        per_pr.append(
            {"pr": pr, "anchor_set": rows[0][0], "severity_mix": rows[0][1],
             "tokens": rows[0][2]}
        )

    p_joint, p_dim, observed, assignments = joint_test(d_tables, args.alpha)
    flagged = sorted(d for d, v in p_dim.items() if v <= args.alpha)
    material = p_joint <= args.alpha

    # p_joint = min_d p_d, so a material verdict always names a dimension.
    # A material verdict with nothing flagged is a comparator bug, not a result.
    if material and not flagged:
        die("comparator bug: material is true but no dimension was flagged")

    json.dump(
        {
            "n_per_arm": n,
            "m_prs": len(prs),
            "assignments": assignments,
            "runs_compared": runs_compared,
            "floor": (2 / math.comb(2 * n, n)) ** len(prs),
            "t_observed": dict(zip(DIMENSIONS, observed)),
            "p_dim": p_dim,
            "p_joint": p_joint,
            "material": material,
            "flagged_dimensions": flagged,
            "per_pr": per_pr,
            "certifies": CERTIFIES,
        },
        sys.stdout,
    )
    sys.stdout.write("\n")
    return 0


def main():
    ap = argparse.ArgumentParser(prog="review-ablation-core.py")
    sub = ap.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("arm")
    a.add_argument("--tree", required=True)
    a.add_argument("--dest", required=True)
    a.add_argument("--arm", required=True)
    a.add_argument("--table", required=True)
    a.add_argument("--spans", default=None)
    a.set_defaults(fn=cmd_arm)

    w = sub.add_parser("write-pins")
    w.add_argument("--tree", required=True)
    w.add_argument("--table", required=True)
    w.set_defaults(fn=cmd_write_pins)

    s = sub.add_parser("stats")
    s.add_argument("--arms", required=True)
    s.add_argument("--alpha", type=float, default=0.05)
    s.set_defaults(fn=cmd_stats)

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
